### ISSUE TITLE
Lea CLI fails due to Import error upon installation with pip

### ISSUE THREAD

**Issue by Emilien-Foissotte** [carbonfact/lea#62]
# Dependencies extras installation are failing

## Issue summary

`lea prepare` or `lea -h` throw a module not found error at execution. 

## Environment

    lea version: 0.5.0
    Database: Duckdb (v1.1.3)
    Python version: 3.11
    Views: Jaffle shop Sample provided cannot work either as CLI fail before being able to execute `lea prepare` or `lea run`
    
 ## Bug reproduction
  
Install the library in a virtual environnement :
```sh
pyenv local 3.11
python -m venv env
source env/bin/activate
pip install lea-cli[duckdb]
```
  
  A warning is thrown : 
  
  ```diff
 Collecting lea-cli[duckdb]
  Downloading lea_cli-0.5.0-py3-none-any.whl.metadata (820 bytes)
+WARNING: lea-cli 0.5.0 does not provide the extra 'duckdb'
 ```
 And doing a 
 
 ```sh
 lea --help
 ```
shows a ImportError : 

```sh
Traceback (most recent call last):
  File "/private/tmp/env/bin/lea", line 5, in <module>
    from lea.main import app
  File "/private/tmp/env/lib/python3.13/site-packages/lea/__init__.py", line 3, in <module>
    from . import cli, clients, diff, views
  File "/private/tmp/env/lib/python3.13/site-packages/lea/clients/__init__.py", line 7, in <module>
    from .bigquery import BigQuery
  File "/private/tmp/env/lib/python3.13/site-packages/lea/clients/bigquery.py", line 7, in <module>
    import pandas_gbq
ModuleNotFoundError: No module named 'pandas_gbq'
```

 It does the same, either installed with `pip install lea-cli[bigquery]` or  basic tool installation `pip install lea-cli`
 
 
## Expected Behavior : 

`lea --help ` shall trigger the manual interface, followed by a successfull `lea prepare  --env .env` and `lea run` using `examples/jaffle_shop` folder  

`.env ` file content :
```env
LEA_USERNAME=emilien

LEA_WAREHOUSE=duckdb
LEA_DUCKDB_PATH=/tmp/lea_duckdb
```

## Proposed solution : 

MR proposed to solve the issue #63

**Comment by Emilien-Foissotte** [comment]
Solved with installation of `lea-cli` version 0.7.3, thank you @MaxHalford !
